### ISSUE TITLE
Search and filtering

### ISSUE THREAD

**Issue by makangus** [Lullabot/copelandia-symfony#2]
Look into the search and ajax filtering functionality.

A few things I would like to figure out
- How to search the drupal content through symfony?
- How to display new content and/or remove old ones (re-render a part of the view with new items)?

**Comment by juampynr** [comment]
For searching, I guess we will have to go for Services module.

Regarding how to implement a live searching experience... I looked in Google for symfony2 ajax search engine and found the following:
- A custom implementation: http://stackoverflow.com/questions/14895904/best-way-to-search-function-in-symfony-2 >> you would have to call Drupal to do the actual search and then show the results.
- Try searching in Github for search engine bundles.

**Comment by mrdavidburns** [comment]
Would it make sense just to make Solr a dependency? Drupal already integrates well with it and by doing so you would be able to get a response back as JSON. Plus it's way faster than MySQL search.

**Comment by sirkitree** [comment]
Solr is typically a requirement on our project anyway, so I would think it makes sense. We even have some stuff in the Angular client that I'd like to do with solr in order to get responses as you type (like we did for mothersclick back in the day) which we could then use on client projects.

**Comment by juampynr** [comment]
Thanks for such a nice suggestion @davexoxide! I think it fits perfectly. I have created https://github.com/Lullabot/copelandia/issues/29 which will handle the Solr set up in the Drupal side.

**Comment by makangus** [comment]
Assuming we using solr, here are few options.
- bypass drupal and talk to solr directly with javascript, this is interesting because this has nothing to do with drupal nor symfony. evolvingweb has a pretty cool js library for it https://github.com/evolvingweb/ajax-solr
- use angular code from the copelandia angular client @sirkitree mentioned, this is even more interesting to use angular just for the search part in a symfony client. There is really nothing wrong with using angular with symfony.
- go through drupal to access solr, expose search api with services http://drupal.org/project/services_search_api or restws http://drupal.org/project/restws_search_api. We will still need javascript for the ajax search so we use angular or straight up jquery.

For the odd chance we are not using Solr
- http://drupal.org/project/services_search would expose the drupal default search, and of course we need to talk to it with javascript.

**Comment by juampynr** [comment]
Since in this project we want to see how much can we get done with Symfony in order to compare this solution with the client based one at the retreat, I would like that we use a Symfony bundle that talks to Solr and renders the results through AJAX.

I do not know which is the best one, but a quick search gave me:
- https://github.com/floriansemm/SolrBundle
- https://github.com/nelmio/NelmioSolariumBundle

A nice site to search: http://knpbundles.com/search?q=solr
Github is also good for searching: https://github.com/search?q=bundle+solr&ref=cmdform&type=Repositories

**Comment by makangus** [comment]
That's true. Then we should pick a solr bundle to talk to solr directly first, so we can do a traditional search. Then we can ajaxify it.
