### ISSUE TITLE
Nginx settings for the copesf.lulladev.com

### ISSUE THREAD

**Issue by juampynr** [Lullabot/copelandia-symfony#4]
I have added some extra settings to the virtual host at /var/nginx/sites-available/copesf.lulladev.com but I am still getting the following unexpected results:
- When opening http://copesf.lulladev.com/app.php and http://copesf.lulladev.com/app_dev.php, the php file is downloaded.
- When opening http://copesf.lulladev.com, "file not found".

@bchavet, can we sync together and have a look at it next week? I may be missing something. Thanks!

**Comment by q0rban** [comment]
@juampy72, I think you need to set the index in the config to app.php.

**Comment by juampynr** [comment]
LOL, someone is already playing with it since there is a swap file alert when I opened it. Will wait a bit to try that @q0rban. Thanks!

**Comment by juampynr** [comment]
Fixed by @bchavet. Yay!
