### ISSUE TITLE
Authenticate registered users

### ISSUE THREAD

**Issue by juampynr** [Lullabot/copelandia-symfony#5]
- Authentication should send both username and password to Drupal (http://copelandia.lulladev.com) to verify credentials.
- Once a user has registered, he should be automatically logged in.
- Once Logged in, the Register Link should turn into Logout.
- When not logged in, a Login link should be available to authenticate him.

**Comment by juampynr** [comment]
Really struggling with this. I tried the tutorial to set up a couple times a custom [Authentication Provider](http://symfony.com/doc/2.2/cookbook/security/custom_authentication_provider.html) and almost suicide myself while debugging its logic.

**Comment by q0rban** [comment]
> Really struggling with this. I tried the tutorial to set up a couple times a custom Authentication Provider and almost suicide myself while debugging its logic.

LOL!
